# Generated by Django 5.2.17 on 2026-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('seeking', models.CharField(choices=[('Female', 'Female (Seeking Women)'), ('Male', 'Male (Seeking Men)')], default='Female', max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('q1_relationship_goal', models.TextField(blank=True, null=True)),
                ('q2_core_values', models.TextField(blank=True, null=True)),
                ('q3_dealbreakers', models.TextField(blank=True, null=True)),
                ('q4_love_language', models.TextField(blank=True, null=True)),
                ('q5_lifestyle_habits', models.TextField(blank=True, null=True)),
                ('q6_conflict_resolution', models.TextField(blank=True, null=True)),
                ('q7_future_vision', models.TextField(blank=True, null=True)),
                ('q8_partner_personality', models.TextField(blank=True, null=True)),
                ('q9_communication_preference', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending Interview', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
