# Generated by Django 5.2.17 on 2026-08-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_matchprofile_is_locked_matchprofile_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprofile',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchprofile',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
