# Generated by Django 5.2.17 on 2026-08-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_matchprofile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchprofile',
            name='used_promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
